### ISSUE TITLE
Something wrong with item currency..

### ISSUE THREAD

**Issue by En0tS** [TheNewEconomy/TNEDocumentation#3]
Get 10 pennies with: **/money give yourName 0.10**:
https://ibb.co/nxTK1L
Then just multiply ingots by mouse wheel:
https://ibb.co/crA7ML
And your balance is:
https://ibb.co/dD3580
This is with default config, all of I changed is
ItemCurrency = true
Material = GOLD_INGOT (minor and major).

Spigot version: 1.12.2 (build 1648), TNE: modified  0.1.1.0 release for 1.12, Vault: 1.7.1-b91.

**Comment by creatorfromhell** [comment]
this was already reported, also this is the documentation repo and not even the correct place to report that.

**Comment by En0tS** [comment]
"not even the correct place to report that" - Sorry about that. So... When it will be fixed?

**Comment by creatorfromhell** [comment]
On the next release.
